### ISSUE TITLE
API-key format invalid

### ISSUE THREAD

**Issue by jesseproudman** [Jakenberg/binance-ruby#9]
Hitting an API format error when trying to grab balance information off an `.info!` call. Will go poke at the code now to see if I can understand what's going on but wanted to raise it up here as well.

```
	 2: from /Users/jproudman/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/binance-ruby-0.2/lib/binance/api.rb:39:in `info!'
	 1: from /Users/jproudman/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/binance-ruby-0.2/lib/binance/api/request.rb:28:in `send!'
/Users/jproudman/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/binance-ruby-0.2/lib/binance/api/request.rb:42:in `process!': (-2014) API-key format invalid. (Binance::Api::Error)
```

**Comment by jesseproudman** [comment]
Entirely me. All good now.
